apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}
    labels:
        suite: fyodorov
        service: tsiolkovsky
spec:
    type: {{ .Values.service.type }}
    ports:
      - port: 8000
        targetPort: 8000
        protocol: TCP
        name: tsiolkovsky
    selector:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
