apiVersion: v2
name: tsiolkovsky-helm
description: A service for managing tools available to models
version: 0.1.2
appVersion: 0.1.0
type: application
dependencies:
  - name: fyodorov-service-base
    version: "0.1.0"
    repository: "file://../../helm/fyodorov-service-base"