# Service-specific configuration for Tsiolkovsky
image:
  repository: "ghcr.io/fyodorovai/tsiolkovsky"
  tag: "main"

service:
  port: 8001

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 500Mi

# Enable ingress with service-specific host
ingress:
  enabled: true
  hosts:
    - tsiolkovsky.danielransom.com

# Environment variables specific to Tsiolkovsky
env: {}