name: Package Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3'

      - name: Package Helm Chart
        run: |
          helm package ./helm

      - name: Publish Helm Chart to GitHub Packages
        uses: helm/chart-releaser-action@v1
        with:
          chart_path: ./*.tgz
          github_token: ${{ secrets.GITHUB_TOKEN }}
