name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.6.3'

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@4.2.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: helm
