name: Package Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Package Helm Chart
        run: |
          helm package ./helm

      - name: Log in to GitHub Packages with Helm registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username USERNAME --password-stdin

      - name: Push Helm Chart
        run: |
            helm push ./*.tgz oci://ghcr.io$/fydorovai/tsiolkovsky

      