name: release
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello! Welcome, and thanks for opening your first issue! We're excited by your contribution and appreciate it!"
          pr-message: "Hello! Welcome, and thanks for opening your first PR! We're grateful for your contribution!"